<?php

namespace AppBundle\Repository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends \Doctrine\ORM\EntityRepository
{
    public function orderDateCroissant()
    {
        return $this->createQueryBuilder('t')
                ->orderBy('t.createdAt', 'ASC')
                ->getQuery();
    }

    public function orderDateDecroissant()
    {
        return $this->createQueryBuilder('t')
                ->orderBy('t.createdAt', 'DESC')
                ->getQuery();
    }

    public function orderByMin($min)
    {
        return $this->createQueryBuilder('m')
                    ->where('m.vote > :min')
                    ->setParameter('min', $min)
                    ->getQuery();
    }
}
